apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaky-server
spec:
  selector:
    matchLabels:
      app: leaky-server
  replicas: 1
  template:
    metadata:
      labels:
        app: leaky-server
    spec:
      containers:
      - name: leaky-server
        # Below line will be replaced in deploy script
        image: LEAKY_SERVER_IMAGE
---
apiVersion: v1
kind: Service
metadata:
  name: leaky-server
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: leaky-server
  selector:
    app: leaky-server
